/-
Current wire-v3 audit root at becfe98e.
Executable partial models and deterministic proofs, NOT full implementation
refinement or cryptographic soundness. See README.md, SCOPE.md and REPORT.md.
Historical models remain in HistoricalAudit.lean and are deliberately not
imported by this current root.
-/
import Audit.Wire3.Arithmetic
import Audit.Wire3.Packed
import Audit.Wire3.Transcript
import Audit.Wire3.Compact
import Audit.Wire3.Sumcheck
import Audit.Wire3.Verifier
import Audit.Wire3.Connections
import Audit.Wire3.WhirTerminal
import Audit.Wire3.WhirFinal
import Audit.Wire3.Merkle
import Audit.Wire3.Norm
import Audit.Wire3.Gates
import Audit.Wire3.Algebra
import Audit.Wire3.Integrated
import Audit.Wire3.GatesAdditionalCoset
import Audit.Wire3.GatesAdditional
import Audit.Wire3.PoseidonConstants
import Audit.Wire3.Poseidon
import Audit.Wire3.GatesComplete
import Audit.Wire3.NormIdentity
import Audit.Wire3.ModularPower
import Audit.Wire3.Spongefish
import Audit.Wire3.WhirInitial
import Audit.Wire3.WhirFinalSpongefish
import Audit.Wire3.WhirPrefix
import Audit.Wire3.PiSharedBits
import Audit.Wire3.PiCache
import Audit.Wire3.GoldilocksCertificate
import Audit.Wire3.MerkleExtraction
import Audit.Wire3.WhirSampling
import Audit.Wire3.WhirRows
import Audit.Wire3.WhirRowBinding
import Audit.Wire3.FermatBridge
import Audit.Wire3.WhirSchedule
import Audit.Wire3.GoldilocksFoundation
import Audit.Wire3.GoldilocksNorm
import Audit.Wire3.GoldilocksExt3Field
import Audit.Wire3.WhirPolynomial
import Audit.Wire3.GoldilocksLagrange
import Audit.Wire3.WhirIntermediate
import Audit.Wire3.WhirDedup
import Audit.Wire3.WhirTail
import Audit.Wire3.GoldilocksDomain
import Audit.Wire3.WhirQuadratic
import Audit.Wire3.WhirParameters
import Audit.Wire3.WhirDomainBridge
import Audit.Wire3.WhirChallenge
import Audit.Wire3.WhirConfigured
import Audit.Wire3.WhirQuicksort
import Audit.Wire3.WhirQuicksortCorrectness
import Audit.Wire3.WhirSamplingExecution
import Audit.Wire3.WhirDomainPower
import Audit.Wire3.OuterRound
import Audit.Wire3.OuterChallenge
import Audit.Wire3.GatePolynomial
import Audit.Wire3.GateBasicPolynomial
import Audit.Wire3.GateMdsPolynomial
import Audit.Wire3.GateCheckedPolynomial
import Audit.Wire3.NormPolynomial
import Audit.Wire3.GateLoopPolynomial
import Audit.Wire3.GateRandomPolynomial
import Audit.Wire3.GateTwelvePolynomial
import Audit.Wire3.WhirRlc
import Audit.Wire3.GateCosetPolynomial
import Audit.Wire3.GatePoseidonPolynomial
import Audit.Wire3.GateAllPolynomial
import Audit.Wire3.GateAggregatePolynomial
import Audit.Wire3.GateSuffixPolynomial
import Audit.Wire3.OuterInterpolation
import Audit.Wire3.OuterInterpolationTotal
import Audit.Wire3.DenseMleIndexed
import Audit.Wire3.OuterInitial
import Audit.Wire3.OuterAdapter
import Audit.Wire3.GateSlotAlgebra
import Audit.Wire3.GateSlotCommutation
import Audit.Wire3.GateSlotRound
import Audit.Wire3.NormDenseRound
import Audit.Wire3.OpenedClaimFold
import Audit.Wire3.GateTerminalBinding
import Audit.Wire3.NormTerminalBinding
import Audit.Wire3.OuterClaimChain
import Audit.Wire3.IntegratedTerminalChain
import Audit.Wire3.EqTableProvenance
import Audit.Wire3.PublicInputHashBinding
import Audit.Wire3.TranscriptProvenance
import Audit.Wire3.VkSubgroupProvenance
import Audit.Wire3.ConditionalSoundness
import Audit.Wire3.GateDenseRound
import Audit.Wire3.OpeningBinding
import Audit.Wire3.ZeroCheckSemantics
import Audit.Wire3.GateClaimChain
import Audit.Wire3.AlphaZeroCheck
import Audit.Wire3.GateRejectionPower
import Audit.Wire3.GateDerivedRejection
import Audit.Wire3.CommitmentOrder
import Audit.Wire3.ChallengeUnionBound
import Audit.Wire3.AttachedUnionBound
import Audit.Wire3.ConstantsProvenance
import Audit.Wire3.JointChallengeSpace
import Audit.Wire3.GatePointZeroCheck
import Audit.Wire3.OuterSequentialConditioning
import Audit.Wire3.InstalledWhirTail
import Audit.Wire3.AdaptiveAgreementFamily
import Audit.Wire3.PinnedWhirProfile
import Audit.Wire3.InstalledIndexSampler
import Audit.Wire3.InstalledInitialTranscript
import Audit.Wire3.InstalledRoundCommit
import Audit.Wire3.ComposedEngine
import Audit.Wire3.InstalledWhirParse
