//! Deterministic canonical WHIR-v2 deployment-profile table.
//!
//! The Solidity verifier receives a flattened `WhirParams` value, while Rust
//! constructs WHIR from higher-level security parameters.  This test derives
//! every supported packed dimension from `WhirPCS::for_constituents`, hashes
//! the exact Solidity `abi.encode(WhirParams)` byte string, and pins both native WHIR
//! protocol-ID halves and the session ID.  The normal test is read-only; set
//! `MLE_WRITE_WHIR_PROFILES_V2=1` to regenerate the Solidity artifact.

use std::fmt::Write as _;
use std::path::Path;

use plonky2_mle::fixture_v2::derive_whir_deployment_profile_for_packed_num_vars_v2;

const MIN_PACKED_NUM_VARIABLES: usize = 1;
const MAX_PACKED_NUM_VARIABLES: usize = 21;
const PROFILE_ENTRY_BYTES: usize = 96;

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(out, "{byte:02x}").unwrap();
    }
    out
}

fn render() -> String {
    let first = derive_whir_deployment_profile_for_packed_num_vars_v2(MIN_PACKED_NUM_VARIABLES)
        .expect("canonical minimum WHIR profile");
    let session_id = first.session_id;
    let mut table = Vec::with_capacity(
        (MAX_PACKED_NUM_VARIABLES - MIN_PACKED_NUM_VARIABLES + 1) * PROFILE_ENTRY_BYTES,
    );
    for num_variables in MIN_PACKED_NUM_VARIABLES..=MAX_PACKED_NUM_VARIABLES {
        let profile = derive_whir_deployment_profile_for_packed_num_vars_v2(num_variables)
            .expect("canonical WHIR profile");
        assert_eq!(profile.session_id, session_id);
        table.extend_from_slice(&profile.parameters_digest);
        table.extend_from_slice(&profile.protocol_id);
    }
    assert_eq!(
        table.len(),
        (MAX_PACKED_NUM_VARIABLES - MIN_PACKED_NUM_VARIABLES + 1) * PROFILE_ENTRY_BYTES
    );

    format!(
        "// SPDX-License-Identifier: MIT OR Apache-2.0\n\
         pragma solidity ^0.8.25;\n\n\
         // @generated by tests/whir_profile_v2_codegen.rs from the canonical Rust\n\
         // WhirPCS::for_constituents profile. Do not edit by hand.\n\n\
         uint256 constant MIN_WHIR_PROFILE_VARIABLES_V2 = {MIN_PACKED_NUM_VARIABLES};\n\
         uint256 constant MAX_WHIR_PROFILE_VARIABLES_V2 = {MAX_PACKED_NUM_VARIABLES};\n\
         uint256 constant WHIR_PROFILE_ENTRY_BYTES_V2 = {PROFILE_ENTRY_BYTES};\n\
         bytes32 constant CANONICAL_WHIR_SESSION_ID_V2 = 0x{};\n\
         bytes constant CANONICAL_WHIR_PROFILE_TABLE_V2 =\n    hex\"{}\";\n",
        hex(&session_id),
        hex(&table),
    )
}

fn write_or_check(path: &Path, expected: &str, write: bool) {
    if write {
        std::fs::write(path, expected)
            .unwrap_or_else(|error| panic!("failed to regenerate {}: {error}", path.display()));
    }
    let actual = std::fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    assert_eq!(actual, expected, "stale canonical WHIR-v2 profile table");
}

#[test]
fn canonical_whir_v2_solidity_profile_table_is_current() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let expected = render();
    let write = std::env::var_os("MLE_WRITE_WHIR_PROFILES_V2").as_deref()
        == Some(std::ffi::OsStr::new("1"));
    write_or_check(
        &manifest.join("contracts/src/generated/WhirProfilesV2.sol"),
        &expected,
        write,
    );
}

#[test]
fn fixture_dimension_ten_profile_is_derived_from_the_same_constructor() {
    let profile = derive_whir_deployment_profile_for_packed_num_vars_v2(10).unwrap();
    let params = profile.params;
    assert_eq!(params.num_variables, 10);
    assert_eq!(params.num_commitments, 3);
    assert_eq!(params.num_vectors, 1);
    assert_eq!(params.rounds.len(), params.num_rounds);
    assert_ne!(profile.parameters_digest, [0u8; 32]);
    assert_ne!(profile.protocol_id, [0u8; 64]);
}
