// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.25;

// Generated by mle/tests/transcript_e2e_trace.rs; do not edit by hand.
// Frozen packed-v1 conformance only; not a production protocol constant.
bytes32 constant PACKED_V1_GOLDEN_TERMINAL_DIGEST = 0x0852dd5c4a3f1bfca1aaa10ca49eff8927b68305bcb360bcf58fca1c8ab0a298;
