// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity ^0.8.25;

import {Test, console} from "forge-std/Test.sol";
import {SpongefishWhirVerify} from "../src/spongefish/SpongefishWhirVerify.sol";
import {SpongefishMerkle} from "../src/spongefish/SpongefishMerkle.sol";
import {GoldilocksExt3} from "../src/spongefish/GoldilocksExt3.sol";
import {PackedClaimLib} from "../src/PackedClaimLib.sol";
import {TranscriptLib} from "../src/TranscriptLib.sol";
import {InvalidMleProof} from "../src/MleProofErrors.sol";
import {
    GROUP_INVERSE_HELPERS,
    GROUP_WITNESS,
    NUM_PCS_CLAIMS,
    NUM_PCS_GROUPS,
    NUM_PCS_TERMINAL_POINTS,
    PACKED_BOUND_CLAIM_MASK,
    POINT_INVERSE
} from "../src/generated/MleWhirV1.sol";

contract WhirRowDecoderHarness {
    function dotOne(bytes calldata row, bool isBaseField) external pure returns (GoldilocksExt3.Ext3 memory) {
        GoldilocksExt3.Ext3[] memory weights = new GoldilocksExt3.Ext3[](1);
        weights[0] = GoldilocksExt3.one();
        SpongefishMerkle.CalldataBytes memory rowView =
            SpongefishMerkle.CalldataBytes({offset: 0, length: row.length});
        assembly ("memory-safe") {
            mstore(rowView, row.offset)
        }
        return SpongefishWhirVerify._dotEqWithRow(weights, rowView, 0, 1, isBaseField);
    }
}

/// @title WhirVerifyTest
/// @notice Tests WHIR verification using fixtures generated by the Rust prover.
///         Uses the v1 grouped-constituent statement exported by the Rust prover.
///         Run: forge test -vvv --match-contract WhirVerifyTest
contract WhirVerifyTest is Test {
    uint256 internal constant P = 0xFFFFFFFF00000001;
    uint256 internal constant HISTORICAL_WIDTH = 160;
    uint256 internal constant HISTORICAL_INDEX_BITS = 8;
    uint256 internal constant HISTORICAL_WITNESS_SLOT = POINT_INVERSE * NUM_PCS_GROUPS + GROUP_WITNESS;
    uint256 internal constant HISTORICAL_INVERSE_SLOT = POINT_INVERSE * NUM_PCS_GROUPS + GROUP_INVERSE_HELPERS;

    struct HistoricalExpected {
        uint256 w0Before;
        uint256 w0After;
        uint256 w1;
        uint256 w80Before;
        uint256 w80After;
        uint256 a0;
        uint256 a1Before;
        uint256 a1After;
        uint256 b0;
    }

    struct HistoricalPcsData {
        bytes protocolId;
        bytes sessionId;
        bytes transcript;
        bytes hints;
        bytes32[] roots;
        SpongefishWhirVerify.WhirParams params;
        GoldilocksExt3.Ext3[] indexPoint;
        GoldilocksExt3.Ext3[] evaluations;
        uint256[] witnessBefore;
        uint256[] witnessAfter;
        uint256[] inverseBefore;
        uint256[] inverseAfter;
    }

    WhirRowDecoderHarness internal immutable rowDecoder = new WhirRowDecoderHarness();

    /// @notice WHIR hints use Arkworks canonical field serialization. Accepting p as an alternate
    ///         encoding of zero would let one field oracle produce multiple Merkle/Fiat-Shamir roots.
    function test_whir_rejects_noncanonical_base_hint_row() public {
        vm.expectRevert();
        rowDecoder.dotOne(hex"01000000ffffffff", true);
    }

    /// @notice Apply the same canonicality rule to every coefficient of an Ext3 hint row.
    function test_whir_rejects_noncanonical_ext3_hint_row() public {
        vm.expectRevert();
        rowDecoder.dotOne(hex"000000000000000001000000ffffffff0000000000000000", false);
    }

    /// @notice Test WHIR verification of a small circuit (degree_bits=2).
    function test_whir_small_mul() public view {
        string memory json = vm.readFile("test/fixtures/small_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a medium circuit (degree_bits=3).
    function test_whir_medium_mul() public view {
        string memory json = vm.readFile("test/fixtures/medium_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a large circuit (degree_bits=4).
    function test_whir_large_mul() public view {
        string memory json = vm.readFile("test/fixtures/large_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a Poseidon hash circuit (degree_bits=2).
    function test_whir_poseidon_hash() public view {
        string memory json = vm.readFile("test/fixtures/poseidon_hash.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification of a recursive circuit (degree_bits=11).
    function test_whir_recursive_verify() public view {
        string memory json = vm.readFile("test/fixtures/recursive_verify.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice Test WHIR verification with degree_bits=13 and multiple rounds.
    /// This exercises the intermediate round code path in SpongefishWhirVerify.
    function test_whir_huge_mul() public view {
        string memory json = vm.readFile("test/fixtures/huge_mul.json");
        _verifyWhirFromFixture(json);
    }

    /// @notice The exact small_mul audit triple is committed into an honest
    /// packed-v1 proof. Replacing only its two derived packed claim cells with
    /// folds of the recorded AFTER constituents must fail at the production
    /// Solidity PCS boundary.
    function test_whir_historical_small_mul_after_only_rejected_at_pcs() public {
        _runHistoricalPcsCase(0);
    }

    /// @notice Same proof-dependent regression for the exact parent-validity
    /// audit triple. This is a PCS-layer fixture, not an attempt to grind the
    /// retired v0 outer Fiat-Shamir challenges into a fresh v1 transcript.
    function test_whir_historical_parent_validity_after_only_rejected_at_pcs() public {
        _runHistoricalPcsCase(1);
    }

    /// @notice Test that a tampered WHIR transcript fails verification.
    function test_whir_tampered_transcript_fails() public {
        string memory json = vm.readFile("test/fixtures/small_mul.json");

        // Parse the WHIR data (unified transcript)
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");

        // Build evaluations [preprocessed, witness]
        GoldilocksExt3.Ext3[] memory evaluations = _parseEvaluations(json);

        // Build WhirParams
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);

        // Tamper with transcript (flip a byte in the middle)
        uint256 mid = transcript.length / 2;
        transcript[mid] = bytes1(uint8(transcript[mid]) ^ 0xFF);

        // Verification should fail
        bool success;
        try this.externalVerifyWhir(
            protocolId, sessionId, transcript, hints, evaluations, _parseRoots(json), params
        ) returns (
            bool result
        ) {
            success = result;
        } catch {
            success = false;
        }
        assertFalse(success, "Tampered transcript should fail WHIR verification");
    }

    function test_whir_bound_statement_rejects_ext3_root_and_point_mutations() public {
        string memory json = vm.readFile("test/fixtures/small_mul.json");
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");
        (GoldilocksExt3.Ext3[] memory evaluations, bytes memory mask) = _parseBoundStatement(json);
        assertEq(evaluations.length, 16, "packed statement must be 4 points x 4 groups");
        assertEq(mask.length, 2, "packed statement mask length");
        assertEq(uint8(mask[0]), 0x7b, "packed statement mask byte 0");
        assertEq(uint8(mask[1]), 0x34, "packed statement mask byte 1");
        bytes32[] memory roots = _parseRoots(json);
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);

        assertTrue(
            this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params)
        );

        // Exercise every terminal-used point/group cell and every Ext3 limb.
        // The mask is the production 4-point x 4-group opening matrix; an
        // unmasked cell is deliberately not asserted by the outer protocol.
        for (uint256 slot = 0; slot < evaluations.length; slot++) {
            if ((uint8(mask[slot >> 3]) & uint8(1 << (slot & 7))) == 0) continue;
            GoldilocksExt3.Ext3 memory originalEvaluation = evaluations[slot];
            for (uint256 limb = 0; limb < 3; limb++) {
                if (limb == 0) {
                    evaluations[slot].c0 = uint64((uint256(originalEvaluation.c0) + 1) % P);
                } else if (limb == 1) {
                    evaluations[slot].c1 = uint64((uint256(originalEvaluation.c1) + 1) % P);
                } else {
                    evaluations[slot].c2 = uint64((uint256(originalEvaluation.c2) + 1) % P);
                }
                vm.expectRevert();
                this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
                evaluations[slot] = originalEvaluation;
            }
        }

        (roots[0], roots[1]) = (roots[1], roots[0]);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        (roots[0], roots[1]) = (roots[1], roots[0]);

        bytes32 originalRoot1 = roots[1];
        roots[1] = roots[0];
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        roots[1] = originalRoot1;

        bytes32[] memory shortRoots = new bytes32[](roots.length - 1);
        for (uint256 i = 0; i < shortRoots.length; i++) {
            shortRoots[i] = roots[i];
        }
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, shortRoots, params);

        bytes32[] memory extendedRoots = new bytes32[](roots.length + 1);
        for (uint256 i = 0; i < roots.length; i++) {
            extendedRoots[i] = roots[i];
        }
        extendedRoots[roots.length] = roots[0];
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, extendedRoots, params);

        GoldilocksExt3.Ext3[] memory shortEvaluations = new GoldilocksExt3.Ext3[](evaluations.length - 1);
        for (uint256 i = 0; i < shortEvaluations.length; i++) {
            shortEvaluations[i] = evaluations[i];
        }
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, shortEvaluations, mask, roots, params);

        GoldilocksExt3.Ext3[] memory extendedEvaluations = new GoldilocksExt3.Ext3[](evaluations.length + 1);
        for (uint256 i = 0; i < evaluations.length; i++) {
            extendedEvaluations[i] = evaluations[i];
        }
        extendedEvaluations[evaluations.length] = evaluations[0];
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, extendedEvaluations, mask, roots, params);

        bytes memory shortMask = new bytes(mask.length - 1);
        shortMask[0] = mask[0];
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, shortMask, roots, params);

        bytes memory wrongSessionId = bytes.concat(sessionId);
        wrongSessionId[0] = bytes1(uint8(wrongSessionId[0]) ^ 1);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, wrongSessionId, transcript, hints, evaluations, mask, roots, params);

        (params.evaluationPoint, params.evaluationPoint2) = (params.evaluationPoint2, params.evaluationPoint);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        (params.evaluationPoint, params.evaluationPoint2) = (params.evaluationPoint2, params.evaluationPoint);

        _reversePoint(params.evaluationPoint);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
    }

    /// @notice Complete the explicit reorder/reuse/mixing matrix around the
    /// grouped statement. Per-limb mutations and exact list shapes are covered
    /// above; this test targets attacks that preserve each element's encoding
    /// while moving it into a different semantic slot.
    function test_whir_bound_statement_rejects_reorder_reuse_and_cross_proof_mixing() public {
        string memory json = vm.readFile("test/fixtures/small_mul.json");
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");
        (GoldilocksExt3.Ext3[] memory evaluations, bytes memory mask) = _parseBoundStatement(json);
        bytes32[] memory roots = _parseRoots(json);
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);
        assertTrue(
            this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params)
        );

        // Every root transposition and every directed cross-group reuse.
        for (uint256 left = 0; left < roots.length; left++) {
            for (uint256 right = left + 1; right < roots.length; right++) {
                (roots[left], roots[right]) = (roots[right], roots[left]);
                vm.expectRevert();
                this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
                (roots[left], roots[right]) = (roots[right], roots[left]);
            }
            for (uint256 source = 0; source < roots.length; source++) {
                if (source == left) continue;
                bytes32 original = roots[left];
                roots[left] = roots[source];
                vm.expectRevert();
                this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
                roots[left] = original;
            }
        }

        // A well-formed root from a different proof is still invalid in each
        // group slot. This is the concrete stale/new commitment-mixing case.
        bytes32[] memory otherRoots = _parseRoots(vm.readFile("test/fixtures/medium_mul.json"));
        for (uint256 group = 0; group < roots.length; group++) {
            assertTrue(otherRoots[group] != roots[group], "fixtures must have distinct roots");
            bytes32 original = roots[group];
            roots[group] = otherRoots[group];
            vm.expectRevert();
            this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
            roots[group] = original;
        }

        // Reordering or duplicating complete, canonical Ext3 claim values is
        // distinct from a malformed-limb attack and must also be rejected.
        assertTrue(!_extEq(evaluations[0], evaluations[1]), "fixture claims must be distinct");
        (evaluations[0], evaluations[1]) = (evaluations[1], evaluations[0]);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        (evaluations[0], evaluations[1]) = (evaluations[1], evaluations[0]);

        GoldilocksExt3.Ext3 memory originalEvaluation = evaluations[1];
        evaluations[1] = evaluations[0];
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        evaluations[1] = originalEvaluation;

        // Exercise permutations involving both additional terminal points,
        // beyond the primary/secondary swap covered by the preceding test.
        (params.additionalEvaluationPoints[0], params.additionalEvaluationPoints[1]) =
        (params.additionalEvaluationPoints[1], params.additionalEvaluationPoints[0]);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        (params.additionalEvaluationPoints[0], params.additionalEvaluationPoints[1]) =
        (params.additionalEvaluationPoints[1], params.additionalEvaluationPoints[0]);

        (params.evaluationPoint, params.additionalEvaluationPoints[0]) =
        (params.additionalEvaluationPoints[0], params.evaluationPoint);
        vm.expectRevert();
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        (params.evaluationPoint, params.additionalEvaluationPoints[0]) =
        (params.additionalEvaluationPoints[0], params.evaluationPoint);

        GoldilocksExt3.Ext3[] memory originalPoint = params.evaluationPoint;
        GoldilocksExt3.Ext3[] memory shortPoint = new GoldilocksExt3.Ext3[](originalPoint.length - 1);
        for (uint256 i = 0; i < shortPoint.length; i++) {
            shortPoint[i] = originalPoint[i];
        }
        params.evaluationPoint = shortPoint;
        vm.expectRevert(SpongefishWhirVerify.InvalidParameters.selector);
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);

        GoldilocksExt3.Ext3[] memory longPoint = new GoldilocksExt3.Ext3[](originalPoint.length + 1);
        for (uint256 i = 0; i < originalPoint.length; i++) {
            longPoint[i] = originalPoint[i];
        }
        longPoint[originalPoint.length] = originalPoint[0];
        params.evaluationPoint = longPoint;
        vm.expectRevert(SpongefishWhirVerify.InvalidParameters.selector);
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, mask, roots, params);
        params.evaluationPoint = originalPoint;

        bytes memory wrongProtocolId = bytes.concat(protocolId);
        wrongProtocolId[0] = bytes1(uint8(wrongProtocolId[0]) ^ 1);
        vm.expectRevert();
        this.externalVerifyWhirBound(wrongProtocolId, sessionId, transcript, hints, evaluations, mask, roots, params);

        bytes memory extendedMask = bytes.concat(mask, hex"00");
        vm.expectRevert(SpongefishWhirVerify.InvalidParameters.selector);
        this.externalVerifyWhirBound(protocolId, sessionId, transcript, hints, evaluations, extendedMask, roots, params);
    }

    /// @notice External wrapper for try/catch (Solidity requires external calls for try).
    function externalVerifyWhir(
        bytes memory protocolId,
        bytes memory sessionId,
        bytes memory transcript,
        bytes memory hints,
        GoldilocksExt3.Ext3[] memory evaluations,
        bytes32[] memory expectedRoots,
        SpongefishWhirVerify.WhirParams memory params
    ) external pure returns (bool) {
        bytes memory evaluationMask = new bytes((evaluations.length + 7) / 8);
        return SpongefishWhirVerify.verifyWhirProofBound(
            protocolId, sessionId, "", transcript, hints, evaluations, evaluationMask, expectedRoots, params
        );
    }

    function externalVerifyWhirBound(
        bytes memory protocolId,
        bytes memory sessionId,
        bytes memory transcript,
        bytes memory hints,
        GoldilocksExt3.Ext3[] memory evaluations,
        bytes memory mask,
        bytes32[] memory expectedRoots,
        SpongefishWhirVerify.WhirParams memory params
    ) external pure returns (bool) {
        return SpongefishWhirVerify.verifyWhirProofBound(
            protocolId, sessionId, "", transcript, hints, evaluations, mask, expectedRoots, params
        );
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  Internal: parse fixture JSON and verify WHIR proof
    // ═══════════════════════════════════════════════════════════════════════

    function _runHistoricalPcsCase(uint256 caseIndex) internal {
        HistoricalPcsData memory data = _loadHistoricalPcsCase(caseIndex);
        _assertHistoricalHonestFolds(data);
        _verifyHistoricalBeforeThenAfter(data);
    }

    function _loadHistoricalPcsCase(uint256 caseIndex) internal view returns (HistoricalPcsData memory data) {
        string memory json = vm.readFile("test/fixtures/historical_pcs_triples.json");
        string memory paramsJson = vm.readFile("test/fixtures/small_mul.json");
        assertEq(vm.parseJsonUint(json, ".schemaVersion"), 1, "historical PCS fixture schema");
        assertEq(vm.parseJsonUint(json, ".degreeBits"), 2, "historical PCS row variables");
        assertEq(vm.parseJsonUint(json, ".constituentWidth"), HISTORICAL_WIDTH, "historical PCS width");
        assertEq(vm.parseJsonUint(json, ".numCommitments"), NUM_PCS_GROUPS, "historical PCS groups");
        assertEq(vm.parseJsonUint(json, ".numLinearForms"), NUM_PCS_TERMINAL_POINTS, "historical PCS points");
        assertEq(vm.parseJsonString(json, ".paramsFixture"), "small_mul.json", "historical PCS config source");

        data.protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        data.sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");
        assertEq(data.protocolId, vm.parseJsonBytes(paramsJson, ".whirProtocolId"), "historical PCS protocol id");
        assertEq(data.sessionId, vm.parseJsonBytes(paramsJson, ".whirSplitSessionId"), "historical PCS split session");

        string memory base = string.concat(".cases[", vm.toString(caseIndex), "]");
        HistoricalExpected memory expected = _historicalExpected(caseIndex);
        string memory expectedName = caseIndex == 0 ? "small_mul" : "parent validity";
        assertEq(vm.parseJsonString(json, string.concat(base, ".name")), expectedName, "historical PCS case");

        data.witnessBefore = _parseGoldilocksArray(json, string.concat(base, ".witnessBefore"));
        data.witnessAfter = _parseGoldilocksArray(json, string.concat(base, ".witnessAfter"));
        data.inverseBefore = _parseGoldilocksArray(json, string.concat(base, ".inverseBefore"));
        data.inverseAfter = _parseGoldilocksArray(json, string.concat(base, ".inverseAfter"));
        _assertHistoricalConstituents(
            data.witnessBefore, data.witnessAfter, data.inverseBefore, data.inverseAfter, expected, HISTORICAL_WIDTH
        );

        data.indexPoint =
            _parseHistoricalExt3Array(json, string.concat(base, ".indexPointAtInverse"), HISTORICAL_INDEX_BITS);
        data.evaluations = _parseHistoricalExt3Array(json, string.concat(base, ".honestEvaluations"), NUM_PCS_CLAIMS);
        data.transcript = vm.parseJsonBytes(json, string.concat(base, ".whirTranscript"));
        data.hints = vm.parseJsonBytes(json, string.concat(base, ".whirHints"));
        data.roots = _parseHistoricalRoots(json, base);
        data.params = _parseWhirParams(paramsJson);
        _setHistoricalPoints(data.params, json, base);
        assertEq(data.params.numVariables, 10, "historical PCS packed variables");
        assertEq(data.params.numVectors, 1, "historical PCS vectors per group");
        assertEq(data.params.numCommitments, NUM_PCS_GROUPS, "historical PCS config groups");
    }

    function _assertHistoricalHonestFolds(HistoricalPcsData memory data) internal pure {
        GoldilocksExt3.Ext3 memory witnessFold =
            PackedClaimLib.fold(data.witnessBefore, HISTORICAL_WIDTH, data.indexPoint);
        GoldilocksExt3.Ext3 memory inverseFold =
            PackedClaimLib.fold(data.inverseBefore, HISTORICAL_WIDTH, data.indexPoint);
        require(_extEq(data.evaluations[HISTORICAL_WITNESS_SLOT], witnessFold), "historical honest witness fold");
        require(_extEq(data.evaluations[HISTORICAL_INVERSE_SLOT], inverseFold), "historical honest inverse fold");
    }

    function _verifyHistoricalBeforeThenAfter(HistoricalPcsData memory data) internal {
        // Use the exact production MLE mask. Both historical target cells are
        // terminal-bound; the other transcript cells remain WHIR-verified.
        bytes memory mask = abi.encodePacked(PACKED_BOUND_CLAIM_MASK);
        bytes32 contextHash = _historicalContextHash(data);
        assertTrue(
            this.externalVerifyWhirBound(
                data.protocolId,
                data.sessionId,
                data.transcript,
                data.hints,
                data.evaluations,
                mask,
                data.roots,
                data.params
            ),
            "historical BEFORE packed-v1 proof"
        );

        GoldilocksExt3.Ext3[] memory forged = new GoldilocksExt3.Ext3[](data.evaluations.length);
        for (uint256 i = 0; i < data.evaluations.length; i++) {
            forged[i] = data.evaluations[i];
        }
        forged[HISTORICAL_WITNESS_SLOT] = PackedClaimLib.fold(data.witnessAfter, HISTORICAL_WIDTH, data.indexPoint);
        forged[HISTORICAL_INVERSE_SLOT] = PackedClaimLib.fold(data.inverseAfter, HISTORICAL_WIDTH, data.indexPoint);
        assertTrue(
            !_extEq(forged[HISTORICAL_WITNESS_SLOT], data.evaluations[HISTORICAL_WITNESS_SLOT]),
            "historical witness projection changed"
        );
        assertTrue(
            !_extEq(forged[HISTORICAL_INVERSE_SLOT], data.evaluations[HISTORICAL_INVERSE_SLOT]),
            "historical inverse projection changed"
        );
        for (uint256 i = 0; i < data.evaluations.length; i++) {
            if (i != HISTORICAL_WITNESS_SLOT && i != HISTORICAL_INVERSE_SLOT) {
                assertTrue(_extEq(forged[i], data.evaluations[i]), "non-historical packed claim changed");
            }
        }

        // InvalidMleProof is emitted by _phaseInitial while it compares the
        // caller's exact AFTER folds against the proof-bound BEFORE cells.
        // All configuration and all proof material are the honest baseline.
        vm.expectRevert(InvalidMleProof.selector);
        this.externalVerifyWhirBound(
            data.protocolId, data.sessionId, data.transcript, data.hints, forged, mask, data.roots, data.params
        );
        assertEq(_historicalContextHash(data), contextHash, "historical proof context mutated");
    }

    function _historicalExpected(uint256 caseIndex) internal pure returns (HistoricalExpected memory expected) {
        if (caseIndex == 0) {
            return HistoricalExpected({
                w0Before: 3_051_498_664_030_569_048,
                w0After: 3_051_498_664_030_569_049,
                w1: 78_509_372_807_566_819,
                w80Before: 6_063_719_204_085_150_528,
                w80After: 2_587_698_932_769_584_699,
                a0: 16_828_114_539_042_804_903,
                a1Before: 7_495_656_216_612_080_666,
                a1After: 14_584_819_668_673_277_578,
                b0: 13_178_207_313_111_168_954
            });
        }
        require(caseIndex == 1, "historical PCS case index");
        return HistoricalExpected({
            w0Before: 8_093_513_556_413_711_660,
            w0After: 8_093_513_556_413_711_661,
            w1: 12_819_036_921_327_938_012,
            w80Before: 2_800_508_231_593_448_274,
            w80After: 15_862_999_140_234_155_880,
            a0: 9_601_097_877_492_032_537,
            a1Before: 17_516_173_920_822_186_472,
            a1After: 6_112_368_312_529_039_975,
            b0: 8_488_046_535_134_267_022
        });
    }

    function _assertHistoricalConstituents(
        uint256[] memory witnessBefore,
        uint256[] memory witnessAfter,
        uint256[] memory inverseBefore,
        uint256[] memory inverseAfter,
        HistoricalExpected memory expected,
        uint256 width
    ) internal pure {
        require(
            witnessBefore.length == width && witnessAfter.length == width && inverseBefore.length == width
                && inverseAfter.length == width,
            "historical PCS constituent length"
        );
        require(witnessBefore[0] == expected.w0Before && witnessAfter[0] == expected.w0After, "historical w0");
        require(witnessBefore[1] == expected.w1 && witnessAfter[1] == expected.w1, "historical w1");
        require(witnessBefore[80] == expected.w80Before && witnessAfter[80] == expected.w80After, "historical w80");
        require(inverseBefore[0] == expected.a0 && inverseAfter[0] == expected.a0, "historical A0");
        require(inverseBefore[1] == expected.a1Before && inverseAfter[1] == expected.a1After, "historical A1");
        require(inverseBefore[80] == expected.b0 && inverseAfter[80] == expected.b0, "historical B0");
        for (uint256 i = 0; i < width; i++) {
            if (i != 0 && i != 80) require(witnessBefore[i] == witnessAfter[i], "extra witness mutation");
            if (i != 1) require(inverseBefore[i] == inverseAfter[i], "extra inverse mutation");
        }
    }

    function _parseHistoricalRoots(string memory json, string memory base)
        internal
        pure
        returns (bytes32[] memory roots)
    {
        roots = new bytes32[](NUM_PCS_GROUPS);
        for (uint256 i = 0; i < roots.length; i++) {
            roots[i] = vm.parseJsonBytes32(json, string.concat(base, ".roots[", vm.toString(i), "]"));
        }
    }

    function _setHistoricalPoints(SpongefishWhirVerify.WhirParams memory params, string memory json, string memory base)
        internal
        pure
    {
        params.evaluationPoint =
            _parseHistoricalExt3Array(json, string.concat(base, ".whirPoints[0]"), params.numVariables);
        params.evaluationPoint2 =
            _parseHistoricalExt3Array(json, string.concat(base, ".whirPoints[1]"), params.numVariables);
        params.additionalEvaluationPoints = new GoldilocksExt3.Ext3[][](2);
        params.additionalEvaluationPoints[0] =
            _parseHistoricalExt3Array(json, string.concat(base, ".whirPoints[2]"), params.numVariables);
        params.additionalEvaluationPoints[1] =
            _parseHistoricalExt3Array(json, string.concat(base, ".whirPoints[3]"), params.numVariables);
    }

    function _historicalContextHash(HistoricalPcsData memory data) internal pure returns (bytes32) {
        return keccak256(
            abi.encode(
                keccak256(data.transcript),
                keccak256(data.hints),
                data.roots,
                data.params.evaluationPoint,
                data.params.evaluationPoint2,
                data.params.additionalEvaluationPoints[0],
                data.params.additionalEvaluationPoints[1]
            )
        );
    }

    function _parseHistoricalExt3Array(string memory json, string memory path, uint256 length)
        internal
        pure
        returns (GoldilocksExt3.Ext3[] memory out)
    {
        out = new GoldilocksExt3.Ext3[](length);
        for (uint256 i = 0; i < length; i++) {
            string memory element = string.concat(path, "[", vm.toString(i), "]");
            out[i] = GoldilocksExt3.Ext3(
                uint64(_parseGoldilocks(json, string.concat(element, ".c0"))),
                uint64(_parseGoldilocks(json, string.concat(element, ".c1"))),
                uint64(_parseGoldilocks(json, string.concat(element, ".c2")))
            );
        }
    }

    function _verifyWhirFromFixture(string memory json) internal view {
        bytes memory transcript = vm.parseJsonBytes(json, ".whirTranscript");
        bytes memory hints = vm.parseJsonBytes(json, ".whirHints");
        bytes memory protocolId = vm.parseJsonBytes(json, ".whirProtocolId");
        bytes memory sessionId = vm.parseJsonBytes(json, ".whirSplitSessionId");

        console.log("WHIR transcript length:", transcript.length);
        console.log("WHIR hints length:", hints.length);
        console.log("Protocol ID length:", protocolId.length);

        // Parse evaluations [preprocessed, witness]
        GoldilocksExt3.Ext3[] memory evaluations = _parseEvaluations(json);
        console.log("Evaluation[0] c0:", evaluations[0].c0);

        // Parse WhirParams
        SpongefishWhirVerify.WhirParams memory params = _parseWhirParams(json);
        console.log("WHIR numVariables:", params.numVariables);
        console.log("WHIR foldingFactor:", params.foldingFactor);
        console.log("WHIR numRounds:", params.numRounds);
        console.log("WHIR numCommitments:", params.numCommitments);

        // Verify
        uint256 gasBefore = gasleft();
        bytes memory evaluationMask = new bytes((evaluations.length + 7) / 8);
        bool valid = SpongefishWhirVerify.verifyWhirProofBound(
            protocolId, sessionId, "", transcript, hints, evaluations, evaluationMask, _parseRoots(json), params
        );
        uint256 gasUsed = gasBefore - gasleft();
        console.log("WHIR verification gas:", gasUsed);

        assertTrue(valid, "WHIR verification should pass");
    }

    function _parseRoots(string memory json) internal pure returns (bytes32[] memory roots) {
        roots = new bytes32[](4);
        roots[0] = vm.parseJsonBytes32(json, ".preprocessedCommitmentRoot");
        roots[1] = vm.parseJsonBytes32(json, ".witnessCommitmentRoot");
        roots[2] = vm.parseJsonBytes32(json, ".inverseHelpersCommitmentRoot");
        roots[3] = vm.parseJsonBytes32(json, ".auxCommitmentRoot");
    }

    function _parseBoundStatement(string memory json)
        internal
        pure
        returns (GoldilocksExt3.Ext3[] memory evaluations, bytes memory mask)
    {
        uint256 width = vm.parseJsonUint(json, ".constituentWidth");
        GoldilocksExt3.Ext3[][] memory indexPoints = _derivePackedIndexPoints(json);
        // Four terminal points by four canonical commitment groups. Each
        // group is one packed vector; constituent slots are folded into its
        // single Ext3 claim after the index challenge is sampled.
        evaluations = new GoldilocksExt3.Ext3[](16);
        mask = new bytes((evaluations.length + 7) / 8);

        _bindPacked(
            evaluations, mask, _parseGoldilocksArray(json, ".preprocessedIndividualEvals"), 0, 0, width, indexPoints[0]
        );
        _bindPacked(
            evaluations, mask, _parseGoldilocksArray(json, ".witnessIndividualEvals"), 0, 1, width, indexPoints[0]
        );
        uint256[] memory auxiliary = new uint256[](2);
        auxiliary[0] = _parseGoldilocks(json, ".auxConstraintEval");
        auxiliary[1] = _parseGoldilocks(json, ".auxPermEval");
        _bindPacked(evaluations, mask, auxiliary, 0, 3, width, indexPoints[0]);

        _bindPacked(
            evaluations,
            mask,
            _parseGoldilocksArray(json, ".preprocessedIndividualEvalsAtRInv"),
            1,
            0,
            width,
            indexPoints[1]
        );
        _bindPacked(
            evaluations, mask, _parseGoldilocksArray(json, ".witnessIndividualEvalsAtRInv"), 1, 1, width, indexPoints[1]
        );
        _bindPacked(
            evaluations, mask, _parseGoldilocksArray(json, ".inverseHelpersEvalsAtRInv"), 1, 2, width, indexPoints[1]
        );
        _bindPacked(
            evaluations, mask, _parseGoldilocksArray(json, ".inverseHelpersEvalsAtRH"), 2, 2, width, indexPoints[2]
        );
        _bindPacked(
            evaluations,
            mask,
            _parseGoldilocksArray(json, ".preprocessedIndividualEvalsAtRGateV2"),
            3,
            0,
            width,
            indexPoints[3]
        );
        _bindPacked(
            evaluations,
            mask,
            _parseGoldilocksArray(json, ".witnessIndividualEvalsAtRGateV2"),
            3,
            1,
            width,
            indexPoints[3]
        );
    }

    function _bindPacked(
        GoldilocksExt3.Ext3[] memory evaluations,
        bytes memory mask,
        uint256[] memory values,
        uint256 point,
        uint256 group,
        uint256 width,
        GoldilocksExt3.Ext3[] memory indexPoint
    ) internal pure {
        uint256 slot = point * 4 + group;
        evaluations[slot] = PackedClaimLib.fold(values, width, indexPoint);
        mask[slot >> 3] = bytes1(uint8(mask[slot >> 3]) | uint8(1 << (slot & 7)));
    }

    function _reversePoint(GoldilocksExt3.Ext3[] memory point) internal pure {
        for (uint256 i = 0; i < point.length / 2; i++) {
            (point[i], point[point.length - 1 - i]) = (point[point.length - 1 - i], point[i]);
        }
    }

    function _extEq(GoldilocksExt3.Ext3 memory left, GoldilocksExt3.Ext3 memory right) internal pure returns (bool) {
        return left.c0 == right.c0 && left.c1 == right.c1 && left.c2 == right.c2;
    }

    function _parseEvaluations(string memory json) internal pure returns (GoldilocksExt3.Ext3[] memory) {
        uint256 numVectors = vm.parseJsonUint(json, ".whirParams.numVectors");
        uint256 numCommitments = vm.parseJsonUint(json, ".whirParams.numCommitments");
        // Four terminal points, group-major constituent rows. The zero mask
        // asks the standalone WHIR test to accept the transcript-bound values
        // as its public statement; MleE2ETest separately checks every terminal
        // coordinate used by the outer protocol.
        return new GoldilocksExt3.Ext3[](4 * numCommitments * numVectors);
    }

    /// @dev Parse a Goldilocks vector of length n from JSON string array.
    function _parseGoldilocksArray(string memory json, string memory path)
        internal
        pure
        returns (uint256[] memory out)
    {
        string[] memory strs = vm.parseJsonStringArray(json, path);
        out = new uint256[](strs.length);
        for (uint256 i = 0; i < strs.length; i++) {
            out[i] = vm.parseUint(strs[i]);
            require(out[i] < P, "fixture: non-canonical Goldilocks element");
        }
    }

    function _parseExactGoldilocksArray(string memory json, string memory path, uint256 expectedLength)
        internal
        pure
        returns (uint256[] memory out)
    {
        out = _parseGoldilocksArray(json, path);
        require(out.length == expectedLength, "fixture: Goldilocks array length");
    }

    function _parseGoldilocks(string memory json, string memory path) internal pure returns (uint256 value) {
        value = vm.parseUint(vm.parseJsonString(json, path));
        require(value < P, "fixture: non-canonical Goldilocks element");
    }

    function _parseWhirParams(string memory json) internal pure returns (SpongefishWhirVerify.WhirParams memory) {
        SpongefishWhirVerify.WhirParams memory params;

        params.numVariables = vm.parseJsonUint(json, ".whirParams.numVariables");
        params.foldingFactor = vm.parseJsonUint(json, ".whirParams.foldingFactor");
        params.numVectors = vm.parseJsonUint(json, ".whirParams.numVectors");
        params.numCommitments = vm.parseJsonUint(json, ".whirParams.numCommitments");
        params.outDomainSamples = vm.parseJsonUint(json, ".whirParams.outDomainSamples");
        params.inDomainSamples = vm.parseJsonUint(json, ".whirParams.inDomainSamples");
        params.initialSumcheckRounds = vm.parseJsonUint(json, ".whirParams.initialSumcheckRounds");
        params.numRounds = vm.parseJsonUint(json, ".whirParams.numRounds");
        params.finalSumcheckRounds = vm.parseJsonUint(json, ".whirParams.finalSumcheckRounds");
        params.finalSize = vm.parseJsonUint(json, ".whirParams.finalSize");
        params.initialCodewordLength = vm.parseJsonUint(json, ".whirParams.initialCodewordLength");
        params.initialMerkleDepth = vm.parseJsonUint(json, ".whirParams.initialMerkleDepth");
        params.initialDomainGenerator = uint64(vm.parseJsonUint(json, ".whirParams.initialDomainGenerator"));
        params.initialInterleavingDepth = vm.parseJsonUint(json, ".whirParams.initialInterleavingDepth");
        params.initialNumVariables = vm.parseJsonUint(json, ".whirParams.initialNumVariables");
        params.initialCosetSize = vm.parseJsonUint(json, ".whirParams.initialCosetSize");
        params.initialNumCosets = vm.parseJsonUint(json, ".whirParams.initialNumCosets");
        params.initialSumcheckPowThreshold =
            uint64(vm.parseUint(vm.parseJsonString(json, ".whirParams.initialSumcheckPowThreshold")));
        params.finalPowThreshold = uint64(vm.parseUint(vm.parseJsonString(json, ".whirParams.finalPowThreshold")));
        params.finalSumcheckPowThreshold =
            uint64(vm.parseUint(vm.parseJsonString(json, ".whirParams.finalSumcheckPowThreshold")));

        // Parse rounds array
        uint256 numRounds = params.numRounds;
        params.rounds = new SpongefishWhirVerify.RoundParams[](numRounds);
        for (uint256 i = 0; i < numRounds; i++) {
            string memory prefix = string.concat(".whirParams.rounds[", vm.toString(i), "]");
            params.rounds[i].codewordLength = vm.parseJsonUint(json, string.concat(prefix, ".codewordLength"));
            params.rounds[i].merkleDepth = vm.parseJsonUint(json, string.concat(prefix, ".merkleDepth"));
            params.rounds[i].domainGenerator = uint64(vm.parseJsonUint(json, string.concat(prefix, ".domainGenerator")));
            params.rounds[i].inDomainSamples = vm.parseJsonUint(json, string.concat(prefix, ".inDomainSamples"));
            params.rounds[i].outDomainSamples = vm.parseJsonUint(json, string.concat(prefix, ".outDomainSamples"));
            params.rounds[i].sumcheckRounds = vm.parseJsonUint(json, string.concat(prefix, ".sumcheckRounds"));
            params.rounds[i].interleavingDepth = vm.parseJsonUint(json, string.concat(prefix, ".interleavingDepth"));
            params.rounds[i].cosetSize = vm.parseJsonUint(json, string.concat(prefix, ".cosetSize"));
            params.rounds[i].numCosets = vm.parseJsonUint(json, string.concat(prefix, ".numCosets"));
            params.rounds[i].numVariables = vm.parseJsonUint(json, string.concat(prefix, ".numVariables"));
            params.rounds[i].powThreshold =
                uint64(vm.parseUint(vm.parseJsonString(json, string.concat(prefix, ".powThreshold"))));
            params.rounds[i].sumcheckPowThreshold =
                uint64(vm.parseUint(vm.parseJsonString(json, string.concat(prefix, ".sumcheckPowThreshold"))));
        }
        string memory roundTail = string.concat(".whirParams.rounds[", vm.toString(numRounds), "].codewordLength");
        try vm.parseJsonUint(json, roundTail) returns (uint256) {
            revert("fixture: WHIR round tail");
        } catch {}

        // Grouped packed WHIR opens four row points. Each is extended by the
        // independently sampled Ext3 constituent-index point before the full
        // dense-LSB point is reversed into WHIR order.
        uint256[] memory rGate = _gatePointFromEvaluationPoint(json);
        uint256[] memory rInv = _parseGoldilocksArray(json, ".invSumcheckChallenges");
        uint256[] memory rH = _parseGoldilocksArray(json, ".hSumcheckChallenges");
        uint256[] memory rGateV2 = _parseGoldilocksArray(json, ".gateSumcheckChallenges");
        GoldilocksExt3.Ext3[][] memory indexPoints = _derivePackedIndexPoints(json);

        params.evaluationPoint = _packedEvaluationPoint(rGate, indexPoints[0]);
        params.evaluationPoint2 = _packedEvaluationPoint(rInv, indexPoints[1]);
        params.additionalEvaluationPoints = new GoldilocksExt3.Ext3[][](2);
        params.additionalEvaluationPoints[0] = _packedEvaluationPoint(rH, indexPoints[2]);
        params.additionalEvaluationPoints[1] = _packedEvaluationPoint(rGateV2, indexPoints[3]);

        return params;
    }

    /// @dev Read sumcheck output point r_gate from the fixture's evaluationPoint
    /// (already embedded as Ext3 with c1=c2=0).
    function _gatePointFromEvaluationPoint(string memory json) internal pure returns (uint256[] memory out) {
        uint256 degreeBits = vm.parseJsonUint(json, ".degreeBits");
        out = new uint256[](degreeBits);
        for (uint256 i = 0; i < degreeBits; i++) {
            string memory base = string.concat(".evaluationPoint[", vm.toString(i), "]");
            out[i] = _parseGoldilocks(json, string.concat(base, ".c0"));
            require(_parseGoldilocks(json, string.concat(base, ".c1")) == 0, "fixture: evaluationPoint c1");
            require(_parseGoldilocks(json, string.concat(base, ".c2")) == 0, "fixture: evaluationPoint c2");
        }
        string memory tail = string.concat(".evaluationPoint[", vm.toString(degreeBits), "].c0");
        try vm.parseJsonString(json, tail) returns (string memory) {
            revert("fixture: evaluationPoint tail");
        } catch {}
    }

    function _derivePackedIndexPoints(string memory json)
        internal
        pure
        returns (GoldilocksExt3.Ext3[][] memory points)
    {
        TranscriptLib.Transcript memory transcript;
        TranscriptLib.init(transcript);
        _replayTranscriptPrefix(transcript, json);

        uint256 degreeBits = vm.parseJsonUint(json, ".degreeBits");
        _replaySumcheck(transcript, json, ".combinedProof", ".evaluationPoint", degreeBits, 3, true);
        TranscriptLib.domainSeparate(transcript, "v2-inv-zerocheck");
        _replaySumcheck(transcript, json, ".invSumcheckProof", ".invSumcheckChallenges", degreeBits, 4, false);
        TranscriptLib.domainSeparate(transcript, "v2-h-linear");
        _replaySumcheck(transcript, json, ".hSumcheckProof", ".hSumcheckChallenges", degreeBits, 2, false);
        TranscriptLib.domainSeparate(transcript, "v2-gate-challenges");
        _squeezeExpectedArray(transcript, _parseExactGoldilocksArray(json, ".tauGate", degreeBits));
        TranscriptLib.domainSeparate(transcript, "v2-gate-zerocheck");
        _replaySumcheck(
            transcript,
            json,
            ".gateSumcheckProof",
            ".gateSumcheckChallenges",
            degreeBits,
            vm.parseJsonUint(json, ".quotientDegreeFactor") + 3,
            false
        );

        TranscriptLib.domainSeparate(transcript, "pcs-eval");
        _absorbPackedClaims(transcript, json);
        TranscriptLib.domainSeparate(transcript, "pcs-constituent-index-v1");

        uint256 indexBits = _ceilLog2(vm.parseJsonUint(json, ".constituentWidth"));
        points = new GoldilocksExt3.Ext3[][](4);
        for (uint256 point = 0; point < 4; point++) {
            points[point] = new GoldilocksExt3.Ext3[](indexBits);
            for (uint256 bit = 0; bit < indexBits; bit++) {
                points[point][bit] = GoldilocksExt3.Ext3(
                    uint64(TranscriptLib.squeezeChallenge(transcript)),
                    uint64(TranscriptLib.squeezeChallenge(transcript)),
                    uint64(TranscriptLib.squeezeChallenge(transcript))
                );
            }
        }
    }

    function _replayTranscriptPrefix(TranscriptLib.Transcript memory transcript, string memory json) internal pure {
        uint256 degreeBits = vm.parseJsonUint(json, ".degreeBits");
        uint256 constituentWidth = vm.parseJsonUint(json, ".constituentWidth");
        TranscriptLib.domainSeparate(transcript, "circuit");
        TranscriptLib.absorbFieldVec(transcript, _parseExactGoldilocksArray(json, ".circuitDigest", 4));
        TranscriptLib.absorbFieldVec(transcript, _parseGoldilocksArray(json, ".publicInputs"));

        TranscriptLib.domainSeparate(transcript, "pcs-schema-packed-v1");
        uint256[10] memory schema = [
            vm.parseJsonUint(json, ".protocolVersion"),
            uint256(4),
            vm.parseJsonUint(json, ".numConstants"),
            vm.parseJsonUint(json, ".numRoutedWires"),
            vm.parseJsonUint(json, ".numWires"),
            constituentWidth,
            _ceilLog2(constituentWidth),
            uint256(1),
            uint256(3),
            uint256(0)
        ];
        for (uint256 i = 0; i < schema.length; i++) {
            TranscriptLib.absorbU64Bytes(transcript, schema[i]);
        }

        TranscriptLib.domainSeparate(transcript, "pcs-group-preprocessed");
        TranscriptLib.absorbBytes(transcript, vm.parseJsonBytes(json, ".preprocessedCommitmentRoot"));
        TranscriptLib.domainSeparate(transcript, "pcs-group-witness");
        TranscriptLib.absorbBytes(transcript, vm.parseJsonBytes(json, ".witnessCommitmentRoot"));
        TranscriptLib.domainSeparate(transcript, "batch-commit-witness");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".witnessBatchR"));
        TranscriptLib.domainSeparate(transcript, "challenges");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".beta"));
        _squeezeExpected(transcript, _parseGoldilocks(json, ".gamma"));
        TranscriptLib.domainSeparate(transcript, "pcs-group-inverse-helpers");
        TranscriptLib.absorbBytes(transcript, vm.parseJsonBytes(json, ".inverseHelpersCommitmentRoot"));
        TranscriptLib.domainSeparate(transcript, "inverse-helpers-batch-r");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".inverseHelpersBatchR"));
        _squeezeExpected(transcript, _parseGoldilocks(json, ".alpha"));
        TranscriptLib.domainSeparate(transcript, "extension-combine");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".extChallenge"));
        TranscriptLib.domainSeparate(transcript, "pcs-group-auxiliary");
        TranscriptLib.absorbBytes(transcript, vm.parseJsonBytes(json, ".auxCommitmentRoot"));
        TranscriptLib.domainSeparate(transcript, "aux-batch-r");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".auxBatchR"));
        TranscriptLib.domainSeparate(transcript, "post-auxiliary-challenges-v1");
        _squeezeExpectedArray(transcript, _parseExactGoldilocksArray(json, ".tau", degreeBits));
        _squeezeExpectedArray(transcript, _parseExactGoldilocksArray(json, ".tauPerm", degreeBits));
        TranscriptLib.domainSeparate(transcript, "v2-logup-challenges");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".lambdaInv"));
        _squeezeExpected(transcript, _parseGoldilocks(json, ".muInv"));
        _squeezeExpectedArray(transcript, _parseExactGoldilocksArray(json, ".tauInv", degreeBits));
        TranscriptLib.domainSeparate(transcript, "combined-sumcheck");
        _squeezeExpected(transcript, _parseGoldilocks(json, ".mu"));
    }

    function _replaySumcheck(
        TranscriptLib.Transcript memory transcript,
        string memory json,
        string memory proofPath,
        string memory challengePath,
        uint256 rounds,
        uint256 evaluationsPerRound,
        bool ext3Point
    ) internal pure {
        uint256[] memory challenges = ext3Point
            ? _gatePointFromEvaluationPoint(json)
            : _parseGoldilocksArray(json, challengePath);
        require(challenges.length == rounds, "fixture: sumcheck challenge length");
        for (uint256 round = 0; round < rounds; round++) {
            TranscriptLib.domainSeparate(transcript, "sumcheck-round");
            string memory roundPath = string.concat(proofPath, ".roundPolys[", vm.toString(round), "]");
            TranscriptLib.absorbFieldVec(transcript, _parseExactGoldilocksArray(json, roundPath, evaluationsPerRound));
            _squeezeExpected(transcript, challenges[round]);
        }
        string memory tail = string.concat(proofPath, ".roundPolys[", vm.toString(rounds), "]");
        try vm.parseJsonStringArray(json, tail) returns (string[] memory) {
            revert("fixture: sumcheck round tail");
        } catch {}
    }

    function _absorbPackedClaims(TranscriptLib.Transcript memory transcript, string memory json) internal pure {
        uint256[] memory empty = new uint256[](0);
        uint256[] memory auxiliary = new uint256[](2);
        uint256 preprocessedLength = vm.parseJsonUint(json, ".numConstants") + vm.parseJsonUint(json, ".numRoutedWires");
        uint256 witnessLength = vm.parseJsonUint(json, ".numWires");
        uint256 inverseLength = 2 * vm.parseJsonUint(json, ".numRoutedWires");
        auxiliary[0] = _parseGoldilocks(json, ".auxConstraintEval");
        auxiliary[1] = _parseGoldilocks(json, ".auxPermEval");
        TranscriptLib.domainSeparate(transcript, "pcs-constituent-claims-v1");
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".preprocessedIndividualEvals", preprocessedLength)
        );
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".witnessIndividualEvals", witnessLength)
        );
        TranscriptLib.absorbFieldVec(transcript, empty);
        TranscriptLib.absorbFieldVec(transcript, auxiliary);
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".preprocessedIndividualEvalsAtRInv", preprocessedLength)
        );
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".witnessIndividualEvalsAtRInv", witnessLength)
        );
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".inverseHelpersEvalsAtRInv", inverseLength)
        );
        TranscriptLib.absorbFieldVec(transcript, empty);
        TranscriptLib.absorbFieldVec(transcript, empty);
        TranscriptLib.absorbFieldVec(transcript, empty);
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".inverseHelpersEvalsAtRH", inverseLength)
        );
        TranscriptLib.absorbFieldVec(transcript, empty);
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".preprocessedIndividualEvalsAtRGateV2", preprocessedLength)
        );
        TranscriptLib.absorbFieldVec(
            transcript, _parseExactGoldilocksArray(json, ".witnessIndividualEvalsAtRGateV2", witnessLength)
        );
        TranscriptLib.absorbFieldVec(transcript, empty);
        TranscriptLib.absorbFieldVec(transcript, empty);
    }

    function _squeezeExpected(TranscriptLib.Transcript memory transcript, uint256 expected) internal pure {
        require(TranscriptLib.squeezeChallenge(transcript) == expected, "fixture: transcript challenge");
    }

    function _squeezeExpectedArray(TranscriptLib.Transcript memory transcript, uint256[] memory expected)
        internal
        pure
    {
        for (uint256 i = 0; i < expected.length; i++) {
            _squeezeExpected(transcript, expected[i]);
        }
    }

    function _ceilLog2(uint256 value) internal pure returns (uint256 bits) {
        require(value != 0, "fixture: zero constituent width");
        value--;
        while (value != 0) {
            bits++;
            value >>= 1;
        }
    }

    function _packedEvaluationPoint(uint256[] memory rowPoint, GoldilocksExt3.Ext3[] memory indexPoint)
        internal
        pure
        returns (GoldilocksExt3.Ext3[] memory point)
    {
        point = new GoldilocksExt3.Ext3[](rowPoint.length + indexPoint.length);
        for (uint256 i = 0; i < indexPoint.length; i++) {
            point[i] = indexPoint[indexPoint.length - 1 - i];
        }
        for (uint256 i = 0; i < rowPoint.length; i++) {
            point[indexPoint.length + i] = GoldilocksExt3.Ext3(uint64(rowPoint[rowPoint.length - 1 - i]), 0, 0);
        }
    }
}
